### ISSUE TITLE
Only Pro Mode available on a Mi9T (davinci) with MicroG LOS

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [h1toru/ANXCameraT#12]
Thx for the v3 fix. Sadly I had still problems.

I am not able to use any other mode then the "Pro" Mode.
Is there a chance to fix that on a davinci?

**Comment by h1toru** [comment]
Can you provide more information? (e.g. Screenshots)

**Comment by h1toru** [comment]
this issue will be closed due to lack of information. also i think this issue similar to #26.
