### ISSUE TITLE
This mod can be improved faster with this

### ISSUE THREAD

**Issue by adamiko741** [h1toru/ANXCameraT#15]
Hi, this is not any issue but if you want, you can check this forgiven github project on MIUI Camera MOD and maybe it can help you in some things because this MOD was great with everything working on it, but after april security update last year camera stopped working at all and I don't know how to fix it, but you have similar project and I hope it would be even better. 
If you want check it: https://github.com/SonalSingh18/vendor_xiaomi_miuicamera
Changelog and magisk module to download: https://www.pling.com/p/1730136/

**Comment by h1toru** [comment]
Thank you for the recommendation, I'll definitely check it out.
