### ISSUE TITLE
And where is the release?

### ISSUE THREAD

**Issue by kilyabin** [h1toru/ANXCameraT#2]

**Comment by Tomblarom** [comment]
Same question....??

**Comment by ilhan-athn7** [comment]
Yea, the repo also does not contain an apk file

**Comment by h1toru** [comment]
> Yea, the repo also does not contain an apk file

The apk size is too large, I can't upload it (for now).

**Comment by h1toru** [comment]
> Yea, the repo also does not contain an apk file

The apk file is too large to be uploaded on GitHub (need [Git LFS](https://git-lfs.com/)). I will upload it ASAP, I just don't have much time right now.

**Comment by sorryusernameisalreadytaken** [comment]
> > Yea, the repo also does not contain an apk file
> 
> The apk file is too large to be uploaded on GitHub (need [Git LFS](https://git-lfs.com/)). I will upload it ASAP, I just don't have much time right now.

Is there a chance to download it from another source and put it into the installable zip?

**Comment by h1toru** [comment]
> > > Yea, the repo also does not contain an apk file
> > 
> > 
> > The apk file is too large to be uploaded on GitHub.
> 
> Is there a chance to download it from another source and put it into the installable zip?
> 
> I see this text file here: https://github.com/h1toru/ANXCameraT/blob/main/system/priv-app/ANXCamera/lib/arm64/AddLibsHere.txt

it is not possible since the apks also modified.

**Comment by h1toru** [comment]
ANXCameraT has been released: https://github.com/h1toru/ANXCameraT/releases/tag/v3.0
