### ISSUE TITLE
Add support for Mi 10 (umi)

### ISSUE THREAD

**Issue by BlastboomStrice** [h1toru/ANXCameraT#23]
Hello, please would it be possible to add support for umi?
I'm running CrDroid 10.2 and here is the kernel https://github.com/umi-development/android_kernel_xiaomi_sm8250 and the xda page https://xdaforums.com/t/xiaomi-mi-10-umi-crdroid-10-2-userdebug-build-stable-will-become-official-soon.4660391/

I don't know how else could I help.

Thank you for time!

**Comment by iCelo-git** [comment]
I also look for some way to install Xiaomi version of camera app on my Mi 10 running custom rom.
I'm currently running TequilaOS Android 13 - https://github.com/tequilaOS/platform_device_xiaomi_umi

Thanks

**Comment by h1toru** [comment]
feature request will be closed for now. i'll give an update when the feature will be added.
