### ISSUE TITLE
Add support for Redmi Note 9S / Redmi Note 9 Pro/Pro/Pro Max / Redmi Note 10 Lite / POCO M2 Pro (curtana, miatoll)

### ISSUE THREAD

**Issue by firat353535** [h1toru/ANXCameraT#24]
Can yolu please add support for resmi note 9s (curtana, miatool) 48 mps model. Thank you for your effort. I couldnt find any module supporting android 14. İ am using lineage OS 21 with android 14

**Comment by h1toru** [comment]
feature request will be closed for now. i'll give an update when the feature will be added.
