### ISSUE TITLE
There are not release

### ISSUE THREAD

**Issue by pilot4u** [h1toru/ANXCameraT#4]
Thank you for your work, I really miss the ANX camera on my A13
How I may help in order to add release?

**Comment by sorryusernameisalreadytaken** [comment]
I would love to see a installable release too.

**Comment by h1toru** [comment]
ANXCameraT has been released: https://github.com/h1toru/ANXCameraT/releases/tag/v3.0

**Comment by h1toru** [comment]
Duplicate #2.
