### ISSUE TITLE
Add Support for Redmi Note 10S / Redmi Note 11 SE / POCO M5S (rosemary)

### ISSUE THREAD

**Issue by XNovaDelta** [h1toru/ANXCameraT#5]
Hi! I would really apreciate if you could add Rosemary to the compatibility list

https://wiki.lineageos.org/devices/rosemary/variant3/

<table class="deviceinfo table">
<tbody>
<tr class="image">
<td colspan="2" style="border-top: 0px;">
<img src="/images/devices/rosemary.png">
<br><br>
<b>Xiaomi Redmi Note 10S Latin America (rosemary)</b>
</td>
</tr>
<tr>
<th scope="row">Released</th>
<td>
April 2021
</td>
</tr>
<tr>
</tr>
<tr>
<th scope="row" colspan="2">Specifications</th>
</tr>
<tr>
<th scope="row">SoC</th>
<td>
Mediatek MT6785 Helio G95
</td>
</tr>
<tr>
<th scope="row">RAM</th>
<td>4/6/8 GB</td>
</tr>
<tr>
<th scope="row">CPU</th>
<td>
Octa-core
Cortex-A76 &amp; Cortex-A55<br>2 x 2.05 GHz + 6 x 2.0 GHz
</td>
</tr>
<tr>
<th scope="row">Architecture</th>
<td>arm64</td>
</tr>
<tr>
<th scope="row">GPU</th>
<td>
ARM Mali-G76 MC4
</td>
</tr>
<tr>
<th scope="row">Network</th>
<td>
<ul>
<li>2G GSM</li>
<li>3G UMTS</li>
<li>4G LTE</li>
</ul>
</td>
</tr>
<tr>
<th scope="row">Storage</th>
<td>64/128 GB</td>
</tr>
<tr>
<th scope="row">Screen</th>
<td>
6.43 in (163.32 mm)<br>
1080x2400 (409 PPI)<br>
AMOLED
</td>
</tr>
<tr>
<th scope="row">Bluetooth</th>
<td>
5.1 with A2DP
</td>
</tr>
<tr>
<th scope="row">Wi-Fi</th>
<td>802.11 a/b/g/n/ac</td>
</tr>
<tr>
<th scope="row">Peripherals</th>
<td><ul>
<li>A-GPS</li>
<li>Accelerometer</li>
<li>Compass</li>
<li>Dual SIM</li>
<li>Dual speakers</li>
<li>Dual-frequency GNSS</li>
<li>Fingerprint reader</li>
<li>BeiDou</li>
<li>Galileo</li>
<li>GLONASS</li>
<li>GPS</li>
<li>Gyroscope</li>
<li>Infrared sensor</li>
<li>Light sensor</li>
<li>Ultrasound proximity sensor</li>
<li>USB OTG</li>
</ul>
</td>
</tr>
<tr>
<th scope="row">Cameras</th>
<td>4
<ul>
<li>
64 MP (wide),
LED flash
</li>
<li>
8 MP (ultrawide),
No flash
</li>
<li>
2 MP (macro),
No flash
</li>
<li>
2 MP (depth),
No flash
</li>
</ul>
</td>
</tr>
<tr>
<th scope="row">Dimensions</th>
<td>
160.5 mm (6.32 in) (h)<br>
74.5 mm (2.93 in) (w)<br>
8.3 mm (0.33 in) (d)
</td>
</tr>
<tr>
<th scope="row">Battery</th>
<td>
Non-removable&nbsp;Li-Po&nbsp;5000 mAh
</td>
</tr>

<tr>
<th scope="row" colspan="2">LineageOS info</th>
</tr>
<tr>
<th scope="row">Maintainer</th>
<td>
<ul>
<li>surblazer</li>
</ul>
</td>
</tr>
<tr>
<th scope="row">Current version</th>
<td>
<ul>
<li>20 (Android 13)</li>
</ul>
</td>
</tr>
</tbody>
</table>

**Comment by XNovaDelta** [comment]
AEONAX added support for Rosemary / Maltose on build 204:
https://camera.aeonax.com/changelogs.html
https://www.pling.com/p/1321115#files-panel

**Comment by h1toru** [comment]
thank you for the information. i'll check that out. @XNovaDelta

**Comment by h1toru** [comment]
feature request will be closed for now. i'll give an update when the feature will be added.
