### ISSUE TITLE
Unable to install on a Mi9T (davinci) with MicroG LOS

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [h1toru/ANXCameraT#9]
Is the latest release ready to install?

I got failed install messages with magisk 26.4 (Zygisk yes & Ramdisk yes). Here is the log:
```
- Copying zip to temp directory
- Installing ANXCameraT-v3.0.zip
/data/user/0/rjah.cpf/cache/flash/update-binary: line 2: 
: not found
/data/user/0/rjah.cpf/cache/flash/update-binary: line 6: 
: not found
/data/user/0/rjah.cpf/cache/flash/update-binary: umask: line 7: illegal mode: 022
/data/user/0/rjah.cpf/cache/flash/update-binary: line 8: 
: not found
/data/user/0/rjah.cpf/cache/flash/update-binary: line 33: syntax error: unexpected end of file (expecting "}")
! Installation failed
```

The same problem when I try to install the ANXCameraT-v3.0.zip with TWRP.
I got:
```
Updater process endet with ERROR: 255
```
![Screenshot_2023-12-31-08-08-48](https://github.com/h1toru/ANXCameraT/assets/12913436/88799cbc-fd5d-4c03-bfa2-7612cfd43ee4)

**Comment by sorryusernameisalreadytaken** [comment]
@quadsteel what did you replaced 🗡️ 

Please help me, I am lost and lazy in 2024. Everything is different now ;O

**Comment by h1toru** [comment]
The problem occurs because of the **End of Line Sequence**. Linux uses `LF` as **EOL Sequence** while Windows uses `CRLF`.

I'm editing the scripts on Windows and sometimes it changed to `CRLF` automatically. That's why the problem occurs.

**Comment by Emirberker** [comment]
first of all happy new year guys (sorry for my bad eng not my first language) I've tried replacing update-binary like @quadsteel (/META-INF/com/google/android/update-binary) script with original anxcams and it didn't work I am getting Updater process endetd with ERROR: 1 in twrp don't know what i am gonna do but really wanna use anx my device is begonia with pixel experience 13

**Comment by h1toru** [comment]
**TWRP**/**Recovery** installation is not supported, installation can be done (only) through *Magisk* or *KernelSU*.

**Comment by h1toru** [comment]
> (Hijacking this post to also ask, if possible, for support for miatoll and/or joyeuse)

Please create/open new issue for feature request.

**Comment by Emirberker** [comment]
> **TWRP**/**Recovery** installation is not supported, installation can be done (only) through _Magisk_ or _KernelSU_.

tried installing via magisk 26.4 nothing changed

**Comment by h1toru** [comment]
This issue have been fixed.

**Please re-download the module and try to install it again**
https://github.com/h1toru/ANXCameraT/releases/tag/v3.0

**Comment by Emirberker** [comment]
> This issue have been fixed.
> 
> **Please re-download the module and try to install it again** https://github.com/h1toru/ANXCameraT/releases/tag/v3.0

thanks man I always wanna to use anxcamera

**Comment by Mjbhatt412** [comment]
![Screenshot_20240402-163842_KernelSU](https://github.com/h1toru/ANXCameraT/assets/165788422/5cc8fa9e-8dda-49ca-a9e6-dac839eea5df)
I installed through kernel SU on A14 . It showing install on module but not apk is not showing in system, please help.
